# Generated by Django 4.1 on 2023-07-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=300)),
                ('other', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatagorie_name', models.CharField(max_length=200)),
                ('catagory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productcatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('actual_price', models.IntegerField(max_length=100)),
                ('discount_price', models.IntegerField()),
                ('description', models.TextField()),
                ('about', models.JSONField()),
                ('subcatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.subcatagory')),
            ],
        ),
    ]
