# Generated by Django 4.1 on 2023-07-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcatagory',
            name='other',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProduImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='productimages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
