# Generated by Django 4.1 on 2023-07-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcatagory',
        ),
        migrations.CreateModel(
            name='Supercatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_catagory', models.CharField(max_length=300)),
                ('sub_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.subcatagory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supcatagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.supercatagory'),
            preserve_default=False,
        ),
    ]
