# Generated by Django 4.1 on 2023-07-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supcatagory',
            new_name='subcatagory',
        ),
    ]
