# Generated by Django 4.1 on 2023-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
