# Generated by Django 4.1 on 2023-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_address_others_alter_addtocart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
