# Generated by Django 4.1 on 2023-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_orderdetail_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
